from fpdf import FPDF
from datetime import datetime
from pathlib import Path
from dataclasses import asdict

class ClinicalReport(FPDF):
    def header(self):
        # Hospital / Lab Header
        self.set_font("Helvetica", "B", 14)
        self.cell(0, 10, "ADVANCED CYTOPATHOLOGY LABORATORY", ln=True, align="C")
        self.set_font("Helvetica", "", 10)
        self.cell(0, 5, "AI-Assisted Cervical Cancer Screening System", ln=True, align="C")
        self.line(10, 30, 200, 30)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by AI-Model v2.1 | Date: {datetime.now().strftime('%Y-%m-%d')}", align="C")

def generate_pdf_report(result, output_path: str):
    pdf = ClinicalReport()
    pdf.add_page()
    
    # --- SECTION 1: Patient & Case Info ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 10, "CASE INFORMATION", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(95, 7, f"Case ID: {result.slide_id}")
    pdf.cell(95, 7, f"Date: {datetime.now().strftime('%d %b %Y')}", ln=True)
    pdf.ln(5)

    # --- SECTION 2: Specimen Adequacy (Your Phase 6 Logic) ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 10, "SPECIMEN ADEQUACY", ln=True)
    pdf.set_font("Helvetica", "", 10)
    
    adequacy_color = (0, 128, 0) if "ADEQUATE" in result.cellularity_status else (200, 0, 0)
    pdf.set_text_color(*adequacy_color)
    pdf.cell(0, 7, f"Status: {result.cellularity_status}", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 7, f"Total Cellularity: {result.total_cells} squamous cells identified.", ln=True)
    pdf.ln(5)

    # --- SECTION 3: FINAL INTERPRETATION ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 10, "FINAL INTERPRETATION / RESULT", ln=True)
    
    # Background color based on risk
    risk_colors = {"HIGH_RISK": (255, 230, 230), "ELEVATED_RISK": (255, 245, 200), "NORMAL": (230, 255, 230)}
    fill_color = risk_colors.get(result.risk_flag, (255, 255, 255))
    
    pdf.set_fill_color(*fill_color)
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 12, f"  {result.risk_flag.replace('_', ' ')}", border=1, ln=True, fill=True)
    pdf.ln(5)

    # --- SECTION 4: Quantitative Findings ---
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 10, "DETAILED QUANTITATIVE ANALYSIS", ln=True)
    pdf.set_font("Helvetica", "", 10)
    
    # Table Header
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(60, 8, "Cell Classification", border=1, fill=True)
    pdf.cell(40, 8, "Count", border=1, fill=True)
    pdf.cell(40, 8, "Percentage (%)", border=1, fill=True, ln=True)
    
    # Table Data
    raw_counts = result.details.get('raw_class_counts', {})
    for cls, count in raw_counts.items():
        percentage = (count / result.total_cells) * 100
        pdf.cell(60, 8, f" {cls}", border=1)
        pdf.cell(40, 8, f" {count}", border=1)
        pdf.cell(40, 8, f" {percentage:.2f}%", border=1, ln=True)
    
    pdf.ln(10)

    # --- SECTION 5: Disclaimer ---
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(0, 5, "DISCLAIMER: This is an automated AI-generated screening report. It is intended for research and triage assistance. Final clinical diagnosis must be confirmed by a board-certified pathologist.")

    pdf.output(output_path)
    return output_path